---
abstract: 'Lucy query extension for NULL values'
author:
  - 'Peter Karman <karman@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: LucyX-Search-NullTermQuery
no_index:
  directory:
    - t
    - inc
requires:
  Data::Dump: 0
  Lucy: 0.003000
  Test::More: 0
  perl: 5.008003
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=LucyX-Search-NullTermQuery
  homepage: https://github.com/karpet/lucyx-search-nulltermquery
  license: http://dev.perl.org/licenses/
  repository: https://github.com/karpet/lucyx-search-nulltermquery
version: 0.003
